# permissions for end users to view luxors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: luxor-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: luxor
    app.kubernetes.io/part-of: luxor
    app.kubernetes.io/managed-by: kustomize
  name: luxor-viewer-role
rules:
- apiGroups:
  - luxor.luxor.test
  resources:
  - luxors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - luxor.luxor.test
  resources:
  - luxors/status
  verbs:
  - get
