---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - luxor.luxor.test
  resources:
  - luxors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - luxor.luxor.test
  resources:
  - luxors/finalizers
  verbs:
  - update
- apiGroups:
  - luxor.luxor.test
  resources:
  - luxors/status
  verbs:
  - get
  - patch
  - update
